### ISSUE TITLE
local path !! :)

### ISSUE THREAD

**Issue by oallouch** [akofman/cordova-plugin-disable-bitcode#1]
Looks like someone forgot to switch to prod when releasing the plugin.
When I do cordova plugin add ..... , I get
Error: ENOENT: no such file or directory, open 'C:\Users\kushi\development\sources\cordova-plugin-disable-bitcode\node_modules\npm\package.json'

**Comment by akofman** [comment]
Wow ... Indeed the dist is bad. Gonna fix it. Thanks !

**Comment by akofman** [comment]
Ok I removed the dist file so now you have to add xcode and cordova-lib devDependencies to your project. 
Then just add this plugin.
